#!/usr/bin/env node
// Builds src/map.js: a simplified equirectangular world land outline from Natural Earth 110m land
// (public domain, naturalearthdata.com), as one SVG path in a 720x360 viewBox. Run: node scripts/build-map.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const URL_LAND = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson';
const W = 720, H = 360, TOL = 0.55, MIN_AREA = 5;

const r = await fetch(URL_LAND, { headers: { 'User-Agent': 'HumanityTimeline/1.0 (https://github.com/dshills/Humanity)' } });
if (!r.ok) throw new Error(r.status + ' ' + URL_LAND);
const geo = await r.json();
const project = ([lon, lat]) => [(lon + 180) / 360 * W, (90 - lat) / 180 * H];

// Douglas-Peucker simplification.
function simplify(pts, tol) {
  if (pts.length < 3) return pts;
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    let max = 0, idx = -1;
    const [ax, ay] = pts[a], [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay, len = Math.hypot(dx, dy) || 1;
    for (let i = a + 1; i < b; i++) {
      const d = Math.abs(dy * pts[i][0] - dx * pts[i][1] + bx * ay - by * ax) / len;
      if (d > max) { max = d; idx = i; }
    }
    if (max > tol && idx > 0) { keep[idx] = 1; stack.push([a, idx], [idx, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}
const area = (pts) => { let s = 0; for (let i = 0; i < pts.length; i++) { const [x1, y1] = pts[i], [x2, y2] = pts[(i + 1) % pts.length]; s += x1 * y2 - x2 * y1; } return Math.abs(s) / 2; };

let d = ''; let rings = 0, points = 0;
for (const f of geo.features) {
  const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const poly of polys) {
    // A closed ring's endpoints coincide, which degenerates Douglas-Peucker: split at the farthest point first.
    const pts = poly[0].map(project);
    let far = 1, best = -1;
    for (let i = 1; i < pts.length - 1; i++) { const dd = Math.hypot(pts[i][0] - pts[0][0], pts[i][1] - pts[0][1]); if (dd > best) { best = dd; far = i; } }
    const ring = simplify(pts.slice(0, far + 1), TOL).concat(simplify(pts.slice(far), TOL).slice(1));
    if (ring.length < 4 || area(ring) < MIN_AREA) continue;
    rings++; points += ring.length;
    d += 'M' + ring.map(([x, y]) => Math.round(x) + ' ' + Math.round(y)).join('L') + 'Z';
  }
}
const out = `(function (root) {
  'use strict';
  const HT = root.HT || (root.HT = {});
  // Generated by scripts/build-map.mjs from Natural Earth 110m land (public domain). Equirectangular:
  // x = (lon + 180) * 2, y = (90 - lat) * 2.
  HT.map = { width: ${W}, height: ${H}, land: '${d}' };
})(typeof window !== 'undefined' ? window : globalThis);
`;
writeFileSync(join(ROOT, 'src/map.js'), out);
console.log(`map.js: ${rings} rings, ${points} points, ${Math.round(out.length / 1024)} KB`);
