#!/usr/bin/env node
// Resolves coordinates for the hand-curated events (src/data/01..08) from Wikidata (CC0) via each event's
// English Wikipedia link, and writes src/geo.js: HT.geo = { "<article title>": [lat, lon, approx] }.
// approx = 1 when the point comes from a related place (location, birthplace) rather than the item itself;
// country-level places are never used.
// Also caches Q-ids and sitelink counts in scripts/cache/wikidata-curated.json for the significance scorer.
// Run: node scripts/import-geo.mjs
import { writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const UA = 'HumanityTimeline/1.0 (https://github.com/dshills/Humanity; import script)';
const PREFIX = 'https://en.wikipedia.org/wiki/';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

require(join(ROOT, 'src/time.js')); require(join(ROOT, 'src/tiers.js'));
for (const f of readdirSync(join(ROOT, 'src/data')).sort()) if (/^0[1-8]-/.test(f)) require(join(ROOT, 'src/data', f));
const events = globalThis.HT.events.filter((e) => e.link && e.link.startsWith(PREFIX));
const titles = [...new Set(events.map((e) => decodeURIComponent(e.link.slice(PREFIX.length)).replace(/_/g, ' ')))];
console.log(`curated events with Wikipedia links: ${events.length} (${titles.length} distinct articles)`);

async function api(params, attempt = 1) {
  const url = 'https://www.wikidata.org/w/api.php?format=json&' + new URLSearchParams(params);
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) { if (attempt < 4) { await sleep(2000 * attempt); return api(params, attempt + 1); } throw new Error(r.status + ' ' + url.slice(0, 120)); }
  return r.json();
}
const coordOf = (ent) => {
  const c = ent && ent.claims && ent.claims.P625 && ent.claims.P625[0] && ent.claims.P625[0].mainsnak.datavalue;
  return c && c.value && c.value.globe && c.value.globe.endsWith('Q2') ? [c.value.latitude, c.value.longitude] : null;
};
// Related places that can stand in for an event's own coordinates. Country-level properties (P17, P495, P27) are
// deliberately absent: a pin at a country's centroid misleads more than it informs (Apollo 11 is not in Kansas).
const FALLBACK = ['P276', 'P131', 'P159', 'P19', 'P119'];
// ...and a related place that is itself a country, state, empire or continent is rejected for the same reason.
const TOO_BROAD = new Set(['Q6256', 'Q3624078', 'Q3024240', 'Q7275', 'Q48349', 'Q5107', 'Q417175', 'Q1250464', 'Q15634554', 'Q35657', 'Q10864048', 'Q82794']);
const refOf = (ent) => {
  for (const p of FALLBACK) {
    const v = ent.claims && ent.claims[p] && ent.claims[p][0] && ent.claims[p][0].mainsnak.datavalue;
    if (v && v.value && v.value.id) return v.value.id;
  }
  return null;
};

const byTitle = new Map();          // title -> { q, sitelinks, coord, ref }
for (let i = 0; i < titles.length; i += 50) {
  const batch = titles.slice(i, i + 50);
  const d = await api({ action: 'wbgetentities', sites: 'enwiki', titles: batch.join('|'), props: 'claims|sitelinks', redirects: 'yes' });
  for (const [q, ent] of Object.entries(d.entities || {})) {
    if (!ent.sitelinks || !ent.sitelinks.enwiki) continue;
    byTitle.set(ent.sitelinks.enwiki.title, { q, sitelinks: Object.keys(ent.sitelinks).length, coord: coordOf(ent), ref: refOf(ent) });
  }
  await sleep(300);
}
// Second pass: coordinates of related places.
const refs = [...new Set([...byTitle.values()].filter((v) => !v.coord && v.ref).map((v) => v.ref))];
const refCoord = new Map();
for (let i = 0; i < refs.length; i += 50) {
  const d = await api({ action: 'wbgetentities', ids: refs.slice(i, i + 50).join('|'), props: 'claims' });
  for (const [q, ent] of Object.entries(d.entities || {})) {
    const classes = ((ent.claims && ent.claims.P31) || []).map((cl) => cl.mainsnak.datavalue && cl.mainsnak.datavalue.value && cl.mainsnak.datavalue.value.id);
    if (classes.some((id) => TOO_BROAD.has(id))) continue;
    const c = coordOf(ent); if (c) refCoord.set(q, c);
  }
  await sleep(300);
}
const geo = {}; const cache = {}; let exact = 0, approx = 0;
for (const t of titles) {
  const v = byTitle.get(t);
  if (!v) continue;
  cache[t] = { q: v.q, sitelinks: v.sitelinks };
  const c = v.coord || (v.ref && refCoord.get(v.ref));
  if (!c) continue;
  if (v.coord) exact++; else approx++;
  geo[t.replace(/ /g, '_')] = [Math.round(c[0] * 10) / 10, Math.round(c[1] * 10) / 10, v.coord ? 0 : 1];
}
const out = `(function (root) {
  'use strict';
  const HT = root.HT || (root.HT = {});
  // Generated by scripts/import-geo.mjs from Wikidata (CC0): coordinates for curated events, keyed by the
  // English Wikipedia article title of the event's link. [lat, lon, approx] — approx = 1 when taken from a
  // related place (location, birthplace, country) rather than the item itself.
  HT.geo = ${JSON.stringify(geo)};
})(typeof window !== 'undefined' ? window : globalThis);
`;
writeFileSync(join(ROOT, 'src/geo.js'), out);
mkdirSync(join(ROOT, 'scripts/cache'), { recursive: true });
writeFileSync(join(ROOT, 'scripts/cache/wikidata-curated.json'), JSON.stringify(cache, null, 0));
console.log(`resolved ${byTitle.size}/${titles.length} articles; coordinates: ${exact} exact + ${approx} approximate; geo.js ${Math.round(out.length / 1024)} KB`);
