#!/usr/bin/env node
// Imports every Nobel Prize (1901–) from api.nobelprize.org (CC0) into src/data/11-nobel.js.
// One event per prize; category by field; dated by the announcement date when known, else 10 December.
// Run: node scripts/import-nobel.mjs   (network access needed at import time only)
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const UA = 'HumanityTimeline/1.0 (https://github.com/dshills/Humanity; import script)';
const CATEGORY = { Physics: 'science', Chemistry: 'science', 'Physiology or Medicine': 'medicine', Literature: 'art', Peace: 'politics', 'Economic Sciences': 'science' };
const SLUG = { Physics: 'physics', Chemistry: 'chemistry', 'Physiology or Medicine': 'medicine', Literature: 'literature', Peace: 'peace', 'Economic Sciences': 'economic-sciences' };
const esc = (s) => String(s)
  .replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r')
  .replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029')
  .replace(/</g, '\\x3c');
const clip = (s, n) => (s.length <= n ? s : s.slice(0, n - 1).replace(/\s+\S*$/, '') + '…');
const cap = (s) => (s ? s.charAt(0).toUpperCase() + s.slice(1) : s);

const prizes = [];
for (let offset = 0; offset < 5000; offset += 100) {                 // hard cap: the API reports ~700 prizes
  const r = await fetch(`https://api.nobelprize.org/2.1/nobelPrizes?limit=100&offset=${offset}`, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`${r.status} nobelPrizes offset ${offset}`);
  const d = await r.json();
  prizes.push(...(d.nobelPrizes || []));
  if (offset + 100 >= d.meta.count) break;
}
const out = [];
for (const p of prizes) {
  const cat = p.category && p.category.en;
  const year = Number(p.awardYear);
  if (!CATEGORY[cat] || !year) continue;
  const laureates = (p.laureates || []).map((l) => (l.knownName && l.knownName.en) || (l.orgName && l.orgName.en) || (l.fullName && l.fullName.en)).filter(Boolean);
  if (!laureates.length) continue;                                   // years with no award
  const [y, m, d] = (p.dateAwarded || `${year}-12-10`).split('-').map(Number);
  const field = cat === 'Economic Sciences' ? 'Economics' : cat === 'Physiology or Medicine' ? 'Medicine' : cat;
  const title = clip(`Nobel Prize in ${field}: ${laureates.join(', ')}`.replace('Nobel Prize in Peace', 'Nobel Peace Prize'), 80).replace(/\.$/, '');   // "Jr." would end the title with a period
  const first = p.laureates[0];
  const motivation = first && first.motivation && first.motivation.en ? cap(first.motivation.en.replace(/^"|"$/g, '')) : '';
  let detail = `${year} ${cat === 'Peace' ? 'Nobel Peace Prize' : `Nobel Prize in ${cat}`}`;
  if (laureates.length > 1) detail += ` to ${laureates.join(', ')}`;
  else detail += ` to ${laureates[0]}`;
  if (motivation) detail += `, ${motivation.charAt(0).toLowerCase() + motivation.slice(1)}`;
  detail = clip(detail, 200).replace(/[.,;:]?…?$/, (m) => (m.endsWith('…') ? '…' : '.'));   // motivations run long; 200 chars keeps the file small
  out.push({ y, m, d, title, detail, category: CATEGORY[cat], link: `https://www.nobelprize.org/prizes/${SLUG[cat]}/${year}/summary/` });
}
out.sort((a, b) => a.y - b.y || a.m - b.m || a.d - b.d);
const seen = new Set();
for (const e of out) { let t = e.title; let k = 2; while (seen.has(t.toLowerCase())) t = clip(e.title, 76) + ` (${k++})`; e.title = t; seen.add(t.toLowerCase()); }
const lines = out.map((e) => `    { t: ymd(${e.y}, ${e.m}, ${e.d}), title: '${esc(e.title)}', tier: 6, category: '${e.category}', detail: '${esc(e.detail)}', link: '${e.link}' }`);
const file = `(function (root) {
  'use strict';
  const HT = root.HT || (root.HT = {});
  const { bce, ce, ymd, ya } = HT.time;
  HT.events = HT.events || [];
  // Generated by scripts/import-nobel.mjs from api.nobelprize.org (CC0): one event per prize, dated by the
  // announcement date. Nobel Prize® is a registered trademark of the Nobel Foundation; the data is used with attribution.
  HT.events.push(
${lines.join(',\n')}
  );
})(typeof window !== 'undefined' ? window : globalThis);
`;
writeFileSync(join(ROOT, 'src/data/11-nobel.js'), file);
console.log(`11-nobel.js: ${out.length} prizes, ${Math.round(file.length / 1024)} KB`);
