(function (root) {
  'use strict';
  const HT = root.HT || (root.HT = {});
  // Generated by scripts/import-objects.mjs: one museum object per selected event, keyed by event title. Objects and
  // their images are CC0 / public domain (The Metropolitan Museum of Art Open Access; The Cleveland Museum of Art Open
  // Access). Images are only ever requested when the panel's Wikimedia/museum image option is switched on.
  HT.objects = {
 "Sumerians invent cuneiform writing at Uruk": {
  "museum": "The Met",
  "title": "Proto-Cuneiform tablet with seal impressions: administrative account of barley distribution with cylinder seal impression of a male figure, ",
  "maker": "Sumerian",
  "date": "ca. 3100–2900 BCE",
  "url": "https://www.metmuseum.org/art/collection/search/329081",
  "img": "https://images.metmuseum.org/CRDImages/an/web-large/DP293243.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Hatshepsut sends a trading expedition to the Land of Punt": {
  "museum": "The Met",
  "title": "Seated Statue of Hatshepsut",
  "maker": "",
  "date": "ca. 1473–1458 BCE",
  "url": "https://www.metmuseum.org/art/collection/search/544450",
  "img": "https://images.metmuseum.org/CRDImages/eg/web-large/DP-24215-002.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Howard Carter finds the tomb of Tutankhamun": {
  "museum": "The Met",
  "title": "Head of Tutankhamun",
  "maker": "",
  "date": "ca. 1328–1318 BCE",
  "url": "https://www.metmuseum.org/art/collection/search/544690",
  "img": "https://images.metmuseum.org/CRDImages/eg/web-large/DT546.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Lydia strikes the first coins in electrum": {
  "museum": "The Met",
  "title": "Gold stater",
  "maker": "Lydian",
  "date": "ca. 560–546 BCE",
  "url": "https://www.metmuseum.org/art/collection/search/252456",
  "img": "https://images.metmuseum.org/CRDImages/gr/web-large/DP-17995-001.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Kofun period begins in Japan with giant keyhole-shaped tombs (c. 250 CE)": {
  "museum": "The Met",
  "title": "Head of a Clay Tomb Sculpture (Haniwa)",
  "maker": "Japan",
  "date": "5th–early 6th century",
  "url": "https://www.metmuseum.org/art/collection/search/44832",
  "img": "https://images.metmuseum.org/CRDImages/as/web-large/DT10526.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Socrates is tried and executed in Athens": {
  "museum": "The Met",
  "title": "The Death of Socrates",
  "maker": "Jacques Louis David",
  "date": "1787",
  "url": "https://www.metmuseum.org/art/collection/search/436105",
  "img": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-13139-001.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Aristotle founds the Lyceum": {
  "museum": "The Met",
  "title": "Aristotle with a Bust of Homer",
  "maker": "Rembrandt (Rembrandt van Rijn)",
  "date": "1653",
  "url": "https://www.metmuseum.org/art/collection/search/437394",
  "img": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-30758-001.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Alexander the Great conquers the Persian Empire": {
  "museum": "The Met",
  "title": "Alexander the Great (?)",
  "maker": "",
  "date": "ring: mid-16th century; cameo: early Hellenistic 4th century BCE",
  "url": "https://www.metmuseum.org/art/collection/search/191486",
  "img": "https://images.metmuseum.org/CRDImages/es/web-large/DP150917.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Siddhartha Gautama, the Buddha, is born in Lumbini": {
  "museum": "The Met",
  "title": "Buddha",
  "maker": "Pakistan, Khyber-Pakhtunkhwa province, possibly Takht-i-bahi monastery, ancient region of Gandhara",
  "date": "3rd century",
  "url": "https://www.metmuseum.org/art/collection/search/646117",
  "img": "https://images.metmuseum.org/CRDImages/as/web-large/DP328363.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Octavian becomes Augustus, the first Roman emperor": {
  "museum": "The Met",
  "title": "Sardonyx cameo portrait of the Emperor Augustus",
  "maker": "Roman",
  "date": "ca. 41–54 CE",
  "url": "https://www.metmuseum.org/art/collection/search/254473",
  "img": "https://images.metmuseum.org/CRDImages/gr/web-large/DP155547.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Moche culture flourishes on the north coast of Peru (c. 100 CE)": {
  "museum": "The Met",
  "title": "Portrait Head Bottle",
  "maker": "Moche",
  "date": "5th–6th century",
  "url": "https://www.metmuseum.org/art/collection/search/308527",
  "img": "https://images.metmuseum.org/CRDImages/ao/web-large/DP-23630-001.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Maya Classic period begins (c. 250 CE)": {
  "museum": "The Met",
  "title": "Whistling vessel",
  "maker": "Maya artist(s)",
  "date": "400–500 CE",
  "url": "https://www.metmuseum.org/art/collection/search/310542",
  "img": "https://images.metmuseum.org/CRDImages/ao/web-large/DP-23468-001.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Chandragupta I founds the Gupta Empire": {
  "museum": "The Met",
  "title": "Standing Buddha Offering Protection",
  "maker": "India (Uttar Pradesh, Mathura)",
  "date": "late 5th century",
  "url": "https://www.metmuseum.org/art/collection/search/38198",
  "img": "https://images.metmuseum.org/CRDImages/as/web-large/DT237.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Hagia Sophia consecrated in Constantinople": {
  "museum": "The Met",
  "title": "Processional Cross",
  "maker": "Byzantine",
  "date": "ca. 1000–1050",
  "url": "https://www.metmuseum.org/art/collection/search/466251",
  "img": "https://images.metmuseum.org/CRDImages/md/web-large/DT121.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Tang dynasty rules a cosmopolitan China": {
  "museum": "Cleveland Museum of Art",
  "title": "Horse",
  "maker": "China, probably Henan province, Tang dynasty (618–907)",
  "date": "late 600s–800",
  "url": "https://clevelandart.org/art/1955.295",
  "img": "https://openaccess-cdn.clevelandart.org/1955.295/1955.295_web.jpg",
  "credit": "The Cleveland Museum of Art, Open Access (CC0)"
 },
 "Viking Age, from the sack of Lindisfarne to Stamford Bridge": {
  "museum": "The Met",
  "title": "Viking Sword",
  "maker": "European, probably Scandinavia",
  "date": "10th century",
  "url": "https://www.metmuseum.org/art/collection/search/24832",
  "img": "https://images.metmuseum.org/CRDImages/aa/web-large/DT758.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Song dynasty leads the world in trade and technology": {
  "museum": "The Met",
  "title": "Finches and bamboo",
  "maker": "Emperor Huizong",
  "date": "early 12th century",
  "url": "https://www.metmuseum.org/art/collection/search/39936",
  "img": "https://images.metmuseum.org/CRDImages/as/web-large/DP151504_CRD.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Murasaki Shikibu completes The Tale of Genji": {
  "museum": "The Met",
  "title": "The Tale of Genji",
  "maker": "Iwasa school",
  "date": "late 17th–early 18th century",
  "url": "https://www.metmuseum.org/art/collection/search/897120",
  "img": "https://images.metmuseum.org/CRDImages/as/web-large/DP-31555-001.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Ferdowsi completes the Shahnameh, the Persian national epic": {
  "museum": "The Met",
  "title": "\"The Feast of Sada\", Folio 22v from the Shahnama (Book of Kings) of Shah Tahmasp",
  "maker": "Abu'l Qasim Firdausi",
  "date": "ca. 1525",
  "url": "https://www.metmuseum.org/art/collection/search/452111",
  "img": "https://images.metmuseum.org/CRDImages/is/web-large/DP107689.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Angkor Wat built by Suryavarman II as a temple to Vishnu": {
  "museum": "Cleveland Museum of Art",
  "title": "Head of a Follower of Shiva",
  "maker": "Cambodia, Angkor, 10th century",
  "date": "900s",
  "url": "https://clevelandart.org/art/2012.294",
  "img": "https://openaccess-cdn.clevelandart.org/2012.294/2012.294_web.jpg",
  "credit": "The Cleveland Museum of Art, Open Access (CC0)"
 },
 "Aztecs found Tenochtitlan on an island in Lake Texcoco": {
  "museum": "The Met",
  "title": "Chalchiuhtlicue",
  "maker": "Mexica artist(s)",
  "date": "1325–1521 CE",
  "url": "https://www.metmuseum.org/art/collection/search/307651",
  "img": "https://images.metmuseum.org/CRDImages/ao/web-large/DP-23817-001.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Inca Empire expands under Pachacuti to rule the Andes": {
  "museum": "The Met",
  "title": "Tunic",
  "maker": "Inca artist(s)",
  "date": "1400–1535 CE",
  "url": "https://www.metmuseum.org/art/collection/search/751901",
  "img": "https://images.metmuseum.org/CRDImages/ao/web-large/DP-14281-001.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Ming dynasty rules China after expelling the Mongols": {
  "museum": "The Met",
  "title": "Jar with dragon",
  "maker": "China",
  "date": "early 15th century",
  "url": "https://www.metmuseum.org/art/collection/search/39666",
  "img": "https://images.metmuseum.org/CRDImages/as/web-large/DP-32251-001.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Columbus reaches the Americas": {
  "museum": "The Met",
  "title": "Portrait of a Man, Said to be Christopher Columbus (born about 1446, died 1506)",
  "maker": "Sebastiano del Piombo (Sebastiano Luciani)",
  "date": "1519",
  "url": "https://www.metmuseum.org/art/collection/search/437645",
  "img": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-17778-001.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Leonardo da Vinci begins the Mona Lisa": {
  "museum": "The Met",
  "title": "A Bear Walking",
  "maker": "Leonardo da Vinci",
  "date": "ca. 1482–85",
  "url": "https://www.metmuseum.org/art/collection/search/459184",
  "img": "https://images.metmuseum.org/CRDImages/rl/web-large/DP324213.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Michelangelo paints the Sistine Chapel ceiling": {
  "museum": "The Met",
  "title": "Studies for the Libyan Sibyl (recto); Studies for the Libyan Sibyl and a small Sketch for a Seated Figure (verso)",
  "maker": "Michelangelo Buonarroti",
  "date": "ca. 1510–11",
  "url": "https://www.metmuseum.org/art/collection/search/337497",
  "img": "https://images.metmuseum.org/CRDImages/dp/web-large/DP826907.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Martin Luther posts the Ninety-five Theses": {
  "museum": "The Met",
  "title": "Portrait of Martin Luther",
  "maker": "Daniel Hopfer",
  "date": "1523",
  "url": "https://www.metmuseum.org/art/collection/search/373105",
  "img": "https://images.metmuseum.org/CRDImages/dp/web-large/DP-20888-001.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Akbar the Great consolidates the Mughal Empire": {
  "museum": "Cleveland Museum of Art",
  "title": "Circumcision ceremony for Akbar’s sons, painting 126 from an Akbar-nama (Book of Akbar) of Abu’l Fazl (Indian, 1551–1602)",
  "maker": "Dharam Das (Indian, active c. 1580–1605)",
  "date": "c. 1602–3",
  "url": "https://clevelandart.org/art/1971.76",
  "img": "https://openaccess-cdn.clevelandart.org/1971.76/1971.76_web.jpg",
  "credit": "The Cleveland Museum of Art, Open Access (CC0)"
 },
 "Tokugawa Ieyasu becomes shogun, unifying Japan under Tokugawa rule": {
  "museum": "The Met",
  "title": "Armor (Gusoku) with Box",
  "maker": "Neo Masanobu 根尾正信",
  "date": "19th century; helmet bowl, early 18th century",
  "url": "https://www.metmuseum.org/art/collection/search/894753",
  "img": "https://images.metmuseum.org/CRDImages/aa/web-large/LC-TR_360_4a_l_2022-020-2-Edit.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Shah Jahan builds the Taj Mahal at Agra": {
  "museum": "The Met",
  "title": "Portrait of Shah Jahan on Horseback",
  "maker": "",
  "date": "19th century",
  "url": "https://www.metmuseum.org/art/collection/search/446577",
  "img": "https://images.metmuseum.org/CRDImages/is/web-large/DT5434.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "United States Declaration of Independence adopted": {
  "museum": "The Met",
  "title": "Washington Crossing the Delaware",
  "maker": "Emanuel Leutze",
  "date": "1851",
  "url": "https://www.metmuseum.org/art/collection/search/11417",
  "img": "https://images.metmuseum.org/CRDImages/ad/web-large/DP215410.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "American Civil War": {
  "museum": "The Met",
  "title": "Prisoners from the Front",
  "maker": "Winslow Homer",
  "date": "1866",
  "url": "https://www.metmuseum.org/art/collection/search/11133",
  "img": "https://images.metmuseum.org/CRDImages/ad/web-large/DT83.jpg",
  "credit": "The Metropolitan Museum of Art, Open Access (CC0)"
 },
 "Meiji Restoration returns power to the emperor of Japan": {
  "museum": "Cleveland Museum of Art",
  "title": "Gathering of Otsu-e Subjects",
  "maker": "Shibata Zeshin (Japanese, 1807–1891)",
  "date": "late 1800s",
  "url": "https://clevelandart.org/art/1982.9",
  "img": "https://openaccess-cdn.clevelandart.org/1982.9/1982.9_web.jpg",
  "credit": "The Cleveland Museum of Art, Open Access (CC0)"
 }
};
})(typeof window !== 'undefined' ? window : globalThis);
